### ISSUE TITLE
How can I create or deallocate vm via telegram bot?

### ISSUE THREAD

**Issue by LexBurner97** [Nihir10dec/telegram-bot#1]
After read your article, I would like to deploy this, but I really wanna to use telegram bot to simply create or deallocate the vm on my azure, is that possible via your method? Pls tell my how to do in order to reach these functions, Thx!

**Comment by Nihir10dec** [comment]
**Yes, it is surely possible with this method**, but it is a long process which we have described in series of 2 articles.
[Part 1](https://rb.gy/bn1ms8) (Here we have explained on how to create  REST API on which being called we can turn on/off our VM. In your case you can create it to create or deallocate it.)
[Part 2](https://rb.gy/yshbnq) (Here we have explained how to create how to create a telegram Bot, and call these API's whenever someone commands the bot to do so.)

Please go through it and let me know if you are stuck in any step. Happy to help.😀

**Comment by Nihir10dec** [comment]
Closing issue after no reply.
